## metallb-pool.yaml
#apiVersion: metallb.io/v1beta1
#kind: IPAddressPool
#metadata:
#  namespace: metallb-system
#  name: default-pool
#  labels:
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/instance: metallb
#  annotations:
#    meta.helm.sh/release-name: metallb
#    meta.helm.sh/release-namespace: metallb-system
#spec:
#  addresses:
#    - 192.168.65.240-192.168.65.250
#---
#apiVersion: metallb.io/v1beta1
#kind: L2Advertisement
#metadata:
#  namespace: metallb-system
#  name: default-l2
#  labels:
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/instance: metallb
#  annotations:
#    meta.helm.sh/release-name: metallb
#    meta.helm.sh/release-namespace: metallb-system
#spec: {}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: default-pool
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: streaming
  annotations:
    meta.helm.sh/release-name: streaming
    meta.helm.sh/release-namespace: streaming
spec:
  addresses:
    - 192.168.65.240-192.168.65.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: default-l2
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: streaming
  annotations:
    meta.helm.sh/release-name: streaming
    meta.helm.sh/release-namespace: streaming
spec: {}
