---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-session-configmaps
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-session-configmaps-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-session-configmaps
subjects:
  - kind: ServiceAccount
    name: {{ .Values.flinkSession.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
